name: Unit Test

on:
  push:
    branches: [master, main]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Echo Hello World
        run: echo "Hello World"
